### ISSUE TITLE
Rendering issue with WebGL + Westeros sink

### ISSUE THREAD

**Issue by wouterlucas** [WebPlatformForEmbedded/WPEWebKit#432]
When using Westeros + Westeros sink in a WebGL based UI the background remains visible, obstructing the video. If you hide the WebKit Wayland client (or change the opacity) the video is playing perfectly.

Tested with BR RPI3 using Westeros + Westeros sink + WPE Compositor. Using a UI made by @basvanmeurs. Tested on WPE WebKit master #382e1c12994a14a9c2a3b3d2c97cb3d59e350e66 using BR #d3fef0125967e0bff27c090fe408802cd179d6bb

It seems to be a rendering issue, if you go into the webinspector and mouse over on the div elements, video comes visible again. Bas added a temporary work around by setting:
```
document.body.style.display = 'none';
document.body.style.display = '';
window.ui.stage.setGlClearColor(0x00000000);
```

Issue is not present on WebKit stable (nov 2016 wk), tested #638821b0b10bef5e3efce24ffb6c29d1f3056986.

**Comment by magomez** [comment]
I've just pushed cad591c5182ee01325d74acbdc8b62c9aabb7394 to wpewebkit to fix this.
The problem was that when using westeros we need to get the video frames size from the sink caps, as we don't have m_sample in MediaPlayerPrivateGStreamerBase. The fix allows to do this if there's no sample available, which is what's done in the stable branch.

Please @wouterlucas tell me if this fixes the issue for you as well.

**Comment by zak211** [comment]
Hi @magomez 
I tried to verify this issue and I still don't see any video
BR# 5a71c49fbaff34d3e696be96323d60c82dc24167
WPEWebKit# cad591c5182ee01325d74acbdc8b62c9aabb7394
UI url used: http://37.153.111.104/future-ui/index.html?720&repair

Notice:
`WPEProcess: tpp.c:84: __pthread_tpp_change_priority: Assertion `new_prio == -1 || (new_prio >= fifo_min_prio && new_prio <= fifo_max_prio)' failed.`

complete console
```
[Tue, 16 Jan 2018 21:03:58 ]:[main.cpp:256]:[<<Global>>] Information: STATE EVENT WidgetsBar "Ready.Apps.Main" appLoaded "Ready.Apps.Main"
[Tue, 16 Jan 2018 21:03:58 ]:[main.cpp:256]:[<<Global>>] Information: STATE EVENT ChannelPlayer "Active" load "Active"
broadcast for surfaceId 2 name noname
[pid=10144][Westeros.cpp:247] : wl_simple_shell_listener.surface_created shell=0xef9650 name=noname surfaceId=2
[pid=10144][Westeros.cpp:257] : wl_simple_shell_listener.surface_created surfaceId=2
DISPATCH [Wayland.cpp:446] virtual bool WPEFramework::Plugin::PlatformImplementation::Dispatch().
[pid=10178][Westeros.cpp:247] : wl_simple_shell_listener.surface_created shell=0x6b1228 name=noname surfaceId=2
[pid=10178][Westeros.cpp:257] : wl_simple_shell_listener.surface_created surfaceId=2
[Tue, 16 Jan 2018 21:03:59 ]:[main.cpp:256]:[<<Global>>] Information: STATE EVENT WidgetsBar "Ready.Apps.Main" appLoaded "Ready.Apps.Main"
[Tue, 16 Jan 2018 21:04:00 ]:[main.cpp:256]:[<<Global>>] Information: STATE EVENT WidgetsBar "Ready.Apps.Main" appLoaded "Ready.Apps.Main"
[Tue, 16 Jan 2018 21:04:06 ]:[main.cpp:256]:[<<Global>>] Information: STATE EVENT ChannelPlayer "Active" start "Active"
gst_westeros_sink_set_property set window rect (0,0,1280,720)
[Tue, 16 Jan 2018 21:04:09 ]:[main.cpp:256]:[<<Global>>] Information: repaired punchhole
gst_westeros_sink_set_property set window rect (0,0,0,0)
gst_westeros_sink_set_property set window rect (0,0,1280,720)
gst_westeros_sink_soc_render: video frame size (1280 x 720)
[Tue, 16 Jan 2018 21:04:24 ]:[main.cpp:256]:[<<Global>>] Information: repaired punchhole
gst_westeros_sink_set_property set window rect (0,0,0,0)
gst_westeros_sink_set_property set window rect (0,0,1280,720)
[pid=10178][Westeros.cpp:143] : wl_keyboard_listener.keyboardKey [0x67, Pressed, 0x20302039 ]
[Tue, 16 Jan 2018 21:04:32 ]:[main.cpp:256]:[<<Global>>] Information: STATE EVENT ChannelBar "Expanded" handleUp "Expanded"
[Tue, 16 Jan 2018 21:04:32 ]:[main.cpp:256]:[<<Global>>] Information: NEW FOCUS PATH
[pid=10178][Westeros.cpp:143] : wl_keyboard_listener.keyboardKey [0x67, Released, 0x20302039 ]
[pid=10178][Westeros.cpp:143] : wl_keyboard_listener.keyboardKey [0x1C, Pressed, 0x20302039 ]
[pid=10178][Westeros.cpp:143] : wl_keyboard_listener.keyboardKey [0x1C, Released, 0x20302039 ]
[Tue, 16 Jan 2018 21:04:35 ]:[main.cpp:256]:[<<Global>>] Information: channel tune
[Tue, 16 Jan 2018 21:04:35 ]:[main.cpp:256]:[<<Global>>] Information: STATE EVENT ChannelBar "Expanded" handleEnter "Expanded"
[Tue, 16 Jan 2018 21:04:35 ]:[main.cpp:256]:[<<Global>>] Information: STATE EVENT WidgetsBar "Ready.Apps.Main" programInfo "NewProgramInfoCollapse"
Westeros Debug: wstISurfaceDestroy resource 0x72c0c530
Westeros Debug: wstDestroySurfaceCallback resource 0x72c0c530 free surfaceInfo
Westeros Debug: wstSurfaceDestroy: surface 0x72c0c688 refCount 1
Westeros Debug: wstDestroySurface: free clientInfo for surface 0x72c0c688
[pid=10144][Westeros.cpp:262] : wl_simple_shell_listener.surface_destroyed shell=0xef9650 name=noname surfaceId=2
[pid=10144][Westeros.cpp:269] : wl_simple_shell_listener.surface_destroyed surfaceId=2
DISPATCH [Wayland.cpp:446] virtual bool WPEFramework::Plugin::PlatformImplementation::Dispatch().
[Tue, 16 Jan 2018 21:04:35 ]:[main.cpp:256]:[<<Global>>] Information: STATE EVENT ChannelPlayer "Active" load "Active"
[Tue, 16 Jan 2018 21:04:35 ]:[main.cpp:256]:[<<Global>>] Information: STATE EVENT ChannelPlayer "Active" error "Active"
Westeros Info: display wayland-0 client pid 10178 disconnected
Westeros Debug: wstDestroySurfaceCallback resource 0x72c0bfa8 free surfaceInfo
Westeros Debug: wstSurfaceDestroy: surface 0x72c0bed8 refCount 1
Westeros Info: display wayland-0 client pid 10178 disconnected
[pid=10144][Westeros.cpp:262] : wl_simple_shell_listener.surface_destroyed shell=0xef9650 name=WebKitBrowser surfaceId=1
[pid=10144][Westeros.cpp:612] : Deinitialize Wayland Surface
WPEProcess: tpp.c:84: __pthread_tpp_change_priority: Assertion `new_prio == -1 || (new_prio >= fifo_min_prio && new_prio <= fifo_max_prio)' failed.
[   88181296 us] FORCED Shutdown: WebKitBrowser by reason: Failure.
[   88187940 us] Deactivated plugin [WebKitBrowser]:[WebKitBrowser]
[   88557022 us] Activated plugin [WebKitBrowser]:[WebKitBrowser]
[pid=10373][Westeros.cpp:738] : Initialize Wayland Display on /tmp/wayland
xkbcommon: ERROR: couldn't find a Compose file for locale "C"
[   99180968 us] FORCED Shutdown: WebKitBrowser by reason: Failure.
[   99187516 us] Deactivated plugin [WebKitBrowser]:[WebKitBrowser]
[   99551970 us] Activated plugin [WebKitBrowser]:[WebKitBrowser]
[pid=10424][Westeros.cpp:738] : Initialize Wayland Display on /tmp/wayland
xkbcommon: ERROR: couldn't find a Compose file for locale "C"
[  110196111 us] FORCED Shutdown: WebKitBrowser by reason: Failure.
[  110217575 us] Deactivated plugin [WebKitBrowser]:[WebKitBrowser]
[  110575133 us] Activated plugin [WebKitBrowser]:[WebKitBrowser]
[pid=10475][Westeros.cpp:738] : Initialize Wayland Display on /tmp/wayland
xkbcommon: ERROR: couldn't find a Compose file for locale "C"
[  121181028 us] FORCED Shutdown: WebKitBrowser by reason: Failure.
[  121197217 us] Deactivated plugin [WebKitBrowser]:[WebKitBrowser]
[  121559015 us] Activated plugin [WebKitBrowser]:[WebKitBrowser]
[pid=10526][Westeros.cpp:738] : Initialize Wayland Display on /tmp/wayland
xkbcommon: ERROR: couldn't find a Compose file for locale "C"
```

**Comment by magomez** [comment]
It was probably a problem with WPEFramework. I've just tested with buildroot version 20be2c2f0f61d3825f98bb966850222bc60bfc0d and wpe version 5a96512b411159c1a820cd191e6b8cbd3b083ffc (both current master) and everything works as expected.

**Comment by albertd** [comment]
Closing, please reopen if still valid
